Repository SOPT-all/35-SOPKATHON-iOS-1stTeam, pull requests merged in 2024-11, with the labels that each got.

#2 [Setting] #1 - 해커톤 전 초기 세팅 진행 했습니다.
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .gitignore
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS.xcodeproj/project.pbxproj
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS.xcworkspace/contents.xcworkspacedata
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/App/AppDelegate.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/App/Base.lproj/LaunchScreen.storyboard
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/App/SceneDelegate.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Extension/UIKit+/UIView+.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Utils/LabelFactory.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Utils/getClassName.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Info.plist
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/.gitkeep
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/ViewController.swift
Labels: Setting ⚙️

#7 [Feat] #6 - 커스텀 버튼 구현 했습니다.
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Extension/UIKit+/UIButton+.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Utils/CustomButton.swift
Labels: Feat🍀

#10 [Feat] #8 - 폰트시스템을 추가 했습니다.
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Fonts/Pretendard-Bold.otf
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Fonts/Pretendard-Light.otf
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Fonts/Pretendard-Medium.otf
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Fonts/Pretendard-Regular.otf
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Literals/FontLiterals.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Utils/CustomButton.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Info.plist
Labels: Setting ⚙️

#17 [Setting] #16 - 컬러 에셋 추가
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/blue.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray100.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray200.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray300.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray400.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray500.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray600.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray700.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/gray800.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/orange3.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/purple100.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/purple200.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/purple300.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/red.colorset/Contents.json
Labels: Setting ⚙️

#18 Feat/#11 네트워크세팅
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Extension/Foundation+/NetworkLoggerPlugin.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Utils/UserDefaultWrapper.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Info.plist
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/.gitkeep
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/Base/AuthInterceptor.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/Base/BaseResponse.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/Base/Config.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/Base/Providers.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/TargetType/AuthTargetType.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/TargetType/QuestionTargetType.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/UserManager.swift
Labels: Setting ⚙️, Feat🍀

#20 [Fix] #19 - API 모델 분리했습니다.
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/API/AnswerAPI.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/API/AuthAPI.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/API/QuestionAPI.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/TargetType/QuestionTargetType.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/UserManager.swift
Labels: Fix⚒️

#21 [Feat] #3 - 질문 공용 컴포넌트 제작
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/tpBlue.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/tpOrange.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Color/tpRed.colorset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Utils/CustomQuestionView.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Utils/QuestionType.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/Onboarding/OnboardingViewController.swift
Labels: Feat🍀

#24 [Feat] #5 - 초대 코드 발급/입력 뷰 구현
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/CopyIcon.imageset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/CopyIcon.imageset/CopyIcon.svg
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/InvitationCode/InputView.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/InvitationCode/InputViewController.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/InvitationCode/ResultView.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/InvitationCode/ResultViewController.swift
Labels: Feat🍀

#26 [Feat] #25 - 점수 확인 뷰 구현
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score0.imageset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score0.imageset/Score0.svg
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score1.imageset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score1.imageset/Score1.svg
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score2.imageset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score2.imageset/Score2.svg
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score3.imageset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/Score/Score3.imageset/Score3.svg
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/Score/ScoreView.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/Score/ScoreViewController.swift
Labels: Feat🍀

#28 [Test] #27 - 테스트 코드 작성과 서버 데이터 타입을 수정 하였습니다.
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS.xcodeproj/project.pbxproj
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/appIcon.png
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/API/AuthAPI.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/Base/Providers.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/TargetType/QuestionTargetType.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/UserManager.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOSTests/QuestionTargetTypeTests.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOSTests/SOPKATHON_4Team_iOSTests.swift
Labels: Test🆙

#30 [Design] #29 - 스플래시 뷰 변경된 디자인 적용
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/BackgroundEffect.imageset/BackgroundEffect.svg
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/BackgroundEffect.imageset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/SplashNameLogo.imageset/Contents.json
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Global/Resource/Assets.xcassets/SplashNameLogo.imageset/SplashNameLogo.svg
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/Splash/SplashViewController.swift
Labels: Design✨

#34 [Feat] #33 - 로그인 서버 통신 로직 구현 했습니다.
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/Base/Config.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/TargetType/AuthTargetType.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Network/TargetType/QuestionTargetType.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/Onboarding/OnboardingViewController.swift
  SOPKATHON-4Team-iOS/SOPKATHON-4Team-iOS/Presentation/Splash/SplashViewController.swift
Labels: Setting ⚙️, Feat🍀
